import streamlit as st

st.set_page_config(
    page_title="LVPEI Carbon Footprint Framework",
    page_icon="🌿",
    layout="wide",
    initial_sidebar_state="expanded",
)

st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=DM+Serif+Display:ital@0;1&display=swap');

html, body, [class*="css"] { font-family: 'Inter', sans-serif; }
.main { background: #F6F9F6; }

.hero {
    background: linear-gradient(135deg, #1A3A1A 0%, #2D6A2D 60%, #3D8B3D 100%);
    border-radius: 16px;
    padding: 3rem 3.5rem;
    color: white;
    margin-bottom: 2rem;
}
.hero-eyebrow {
    font-size: 0.78rem;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.12em;
    color: #A8D5A8;
    margin-bottom: 0.8rem;
}
.hero-title {
    font-family: 'DM Serif Display', serif;
    font-size: 2.8rem;
    line-height: 1.15;
    margin-bottom: 1rem;
    color: white;
}
.hero-sub {
    font-size: 1.05rem;
    color: #C5E8C5;
    line-height: 1.7;
    max-width: 680px;
    margin-bottom: 1.5rem;
}
.hero-badge {
    display: inline-block;
    background: rgba(255,255,255,0.15);
    border: 1px solid rgba(255,255,255,0.25);
    border-radius: 999px;
    padding: 0.3rem 0.9rem;
    font-size: 0.8rem;
    color: #E0F0E0;
    margin-right: 0.5rem;
    margin-bottom: 0.4rem;
}

.card {
    background: white;
    border-radius: 14px;
    padding: 1.6rem;
    height: 100%;
    box-shadow: 0 1px 6px rgba(0,0,0,0.06);
    border-top: 4px solid #2D6A2D;
    transition: box-shadow 0.2s;
}
.card:hover { box-shadow: 0 4px 16px rgba(0,0,0,0.10); }
.card-icon { font-size: 1.8rem; margin-bottom: 0.6rem; }
.card-title {
    font-family: 'DM Serif Display', serif;
    font-size: 1.15rem;
    color: #1A3A1A;
    margin-bottom: 0.4rem;
}
.card-body { font-size: 0.88rem; color: #5A7A5A; line-height: 1.65; }
.card-campus {
    font-size: 0.75rem;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.08em;
    color: #2D6A2D;
    margin-top: 0.8rem;
}

.eq-box {
    background: #EEF6EE;
    border: 1px solid #C5DCC5;
    border-radius: 12px;
    padding: 1.4rem 1.8rem;
    margin: 1.5rem 0;
    font-family: 'DM Serif Display', serif;
    font-size: 1.1rem;
    color: #1A3A1A;
    text-align: center;
}
.eq-note { font-family: 'Inter', sans-serif; font-size: 0.82rem; color: #5A7A5A; margin-top: 0.5rem; }

.team-row {
    background: white;
    border-radius: 12px;
    padding: 1.2rem 1.6rem;
    display: flex;
    align-items: center;
    gap: 1rem;
    box-shadow: 0 1px 4px rgba(0,0,0,0.05);
    margin-bottom: 0.8rem;
}
.team-name { font-weight: 600; color: #1A3A1A; font-size: 0.95rem; }
.team-role { font-size: 0.82rem; color: #5A7A5A; }

.scope-pill {
    display: inline-block;
    padding: 0.2rem 0.7rem;
    border-radius: 999px;
    font-size: 0.75rem;
    font-weight: 600;
    margin-right: 0.3rem;
}
.s1 { background: #FDE8D8; color: #8B4513; }
.s2 { background: #D8EAF5; color: #1A5276; }
.s3 { background: #D5F5E3; color: #1A5C2A; }

.footer {
    font-size: 0.78rem;
    color: #8A9E8A;
    text-align: center;
    padding: 1.5rem 0 0.5rem;
    border-top: 1px solid #C5DCC5;
    margin-top: 2rem;
}
</style>
""", unsafe_allow_html=True)

# ── HERO ──────────────────────────────────────────────────────────────────────
st.markdown("""
<div class="hero">
    <div class="hero-eyebrow">LV Prasad Eye Institute · PS-I Research Internship 2025–26</div>
    <div class="hero-title">Tele-ophthalmology<br>Carbon Footprint Framework</div>
    <div class="hero-sub">
        A patient-level lifecycle assessment of the carbon savings generated by teleconsultation
        screening at LVPEI Vision Centres, and the facility emissions of in-person ophthalmic
        care at KAR Campus — combined into one full patient journey.
    </div>
    <span class="hero-badge">GHG Protocol Scope 1/2/3</span>
    <span class="hero-badge">ISO 14040/14044 LCA</span>
    <span class="hero-badge">CEA v21.0 Grid Factor</span>
    <span class="hero-badge">Rani et al. 2024</span>
    <span class="hero-badge">Kwon/Thiel 2024</span>
</div>
""", unsafe_allow_html=True)

# ── CALCULATOR CARDS ──────────────────────────────────────────────────────────
st.markdown("### What's inside")
c1, c2, c3 = st.columns(3)

with c1:
    st.markdown("""
    <div class="card">
        <div class="card-icon">📡</div>
        <div class="card-title">Tele-ophthalmology Calculator</div>
        <div class="card-body">
            Per-patient CO₂ <strong>saved</strong> by teleconsultation screening — travel
            avoided, device electricity, DICOM data overhead. Upload an eyeSmart CSV
            export or explore with 50 simulated patients.
        </div>
        <div class="card-campus">GPR Vision Centre · Kismathpur</div>
    </div>
    """, unsafe_allow_html=True)

with c2:
    st.markdown("""
    <div class="card">
        <div class="card-icon">🏥</div>
        <div class="card-title">Ophthalmology Calculator</div>
        <div class="card-body">
            Per-case CO₂ <strong>emitted</strong> by facility-based care — surgery devices,
            CSSD sterilisation, consumables, pharmaceuticals, and waste disposal across
            cataract and DR/IVI pathways.
        </div>
        <div class="card-campus">KAR Campus · Shlok Marda</div>
    </div>
    """, unsafe_allow_html=True)

with c3:
    st.markdown("""
    <div class="card">
        <div class="card-icon">🔗</div>
        <div class="card-title">Combined Patient Journey</div>
        <div class="card-body">
            One patient, end to end. Teleconsultation screening → diagnosis →
            treatment. Net carbon footprint = treatment emissions minus screening
            savings. The full story in a single number.
        </div>
        <div class="card-campus">Both campuses · Joint view</div>
    </div>
    """, unsafe_allow_html=True)

# ── MASTER EQUATION ───────────────────────────────────────────────────────────
st.markdown("""
<div class="eq-box">
    ΔE = E<sub>counterfactual</sub> &minus; E<sub>teleconsultation</sub>
    <div class="eq-note">
        ΔE &gt; 0 → carbon saved by teleconsultation &nbsp;|&nbsp;
        Functional unit: 1 completed teleconsultation episode, kgCO₂e &nbsp;|&nbsp;
        Dominant term: patient travel avoided (Scope 3)
    </div>
</div>
""", unsafe_allow_html=True)

# ── SCOPE BREAKDOWN ───────────────────────────────────────────────────────────
st.markdown("### GHG Protocol scope classification")
s1, s2, s3 = st.columns(3)
with s1:
    st.markdown("""
    <span class="scope-pill s1">Scope 1</span>
    <br><br>
    <strong>Direct combustion</strong><br>
    Diesel generator at GPR Vision Centre.<br><br>
    <em>Status: Zero — facility runs 100% on Telangana state grid (confirmed on-site).</em>
    """, unsafe_allow_html=True)
with s2:
    st.markdown("""
    <span class="scope-pill s2">Scope 2</span>
    <br><br>
    <strong>Purchased electricity</strong><br>
    Diagnostic device electricity during a teleconsultation session (10 min, 205W assumed load).<br><br>
    <em>Grid EF: 0.7117 kgCO₂/kWh — CEA v21.0, FY 2024-25.</em>
    """, unsafe_allow_html=True)
with s3:
    st.markdown("""
    <span class="scope-pill s3">Scope 3</span>
    <br><br>
    <strong>Value chain emissions</strong><br>
    Patient travel avoided (dominant), DICOM data transmission, EMR overhead,
    consumables, pharmaceuticals, waste disposal.<br><br>
    <em>Travel savings: Rani et al. 2024 modal EFs.</em>
    """, unsafe_allow_html=True)

st.markdown("<br>", unsafe_allow_html=True)

# ── KEY NUMBERS ───────────────────────────────────────────────────────────────
st.markdown("### Locked assumptions")
k1, k2, k3, k4 = st.columns(4)
k1.metric("Grid emission factor", "0.7117 kg CO₂/kWh", "CEA v21.0, FY 2024-25")
k2.metric("Session duration", "10 min", "Midpoint, Dr. Rani 5–15 min range")
k3.metric("Triage: Green / Yellow / Red", "84 / 8 / 8 %", "Rani et al. 2024")
k4.metric("Tree absorption", "21 kg CO₂/year", "Per tree, literature standard")

st.markdown("<br>", unsafe_allow_html=True)

# ── TEAM ──────────────────────────────────────────────────────────────────────
st.markdown("### Project team")
t1, t2 = st.columns(2)
with t1:
    st.markdown("""
    <div class="team-row">
        <div>
            <div class="team-name">Daiwik Singh &nbsp;<span style="font-weight:400;color:#8A9E8A">2024B1A41063H</span></div>
            <div class="team-role">Tele-ophthalmology Carbon Footprint · GPR Vision Centre · B.E. Biological Sciences + M.Sc. Finance</div>
        </div>
    </div>
    <div class="team-row">
        <div>
            <div class="team-name">Shlok Marda &nbsp;<span style="font-weight:400;color:#8A9E8A">2024B1A40944H</span></div>
            <div class="team-role">Facility-based Ophthalmology Carbon Calculator · KAR Campus</div>
        </div>
    </div>
    """, unsafe_allow_html=True)
with t2:
    st.markdown("""
    <div class="team-row">
        <div>
            <div class="team-name">Dr. Padmaja Kumari Rani</div>
            <div class="team-role">Network Associate Director, Tele-ophthalmology · LVPEI · PS-I Supervisor</div>
        </div>
    </div>
    <div class="team-row">
        <div>
            <div class="team-name">Prof. Niranjan Swain</div>
            <div class="team-role">Faculty In-Charge · BITS Pilani, Hyderabad Campus</div>
        </div>
    </div>
    """, unsafe_allow_html=True)

# ── LITERATURE ────────────────────────────────────────────────────────────────
with st.expander("📚 Key literature & data sources"):
    st.markdown("""
    | # | Reference | Role in this framework |
    |---|---|---|
    | 1 | **Rani et al. 2024** — Eye/Nature | Primary transport modal EFs; triage distribution; travel distance bands. BMJ South Asia Award 2024-25. |
    | 2 | **Kwon/Thiel 2024** — JMIR | EMR vs. paper LCA at Aravind; digital overhead benchmark (0.361 kgCO₂/patient on Indian grid). |
    | 3 | **Thiel et al. 2017** — JCRS | Cataract surgery LCA at Aravind; CSSD as dominant emission source; benchmark (5.89 kg/case). |
    | 4 | **van der Zee et al. 2024** — Health Services Insights | Systematic review of 33 telemedicine carbon studies; validates travel as dominant term. |
    | 5 | **CEA CO₂ Baseline Database v21.0** (Nov 2025) | Grid EF 0.7117 kgCO₂/kWh, FY 2024-25 national weighted average. |
    | 6 | **GHG Protocol Corporate Standard** | Scope 1/2/3 classification framework. |
    | 7 | **ISO 14040/14044** | LCA methodology; functional unit definition. |
    | 8 | **IPCC 2006 Guidelines Vol. 2** | Diesel combustion EF (2.68 kgCO₂e/L). |
    """)

st.markdown('<div class="footer">BITS Pilani Hyderabad Campus · Practice School-I 2025–26 · LV Prasad Eye Institute · Joint project under Dr. Padmaja Kumari Rani</div>', unsafe_allow_html=True)
